export type { User, UserRole, UserCredentials, UserAvatar } from "./types";
export {
  userSchema,
  userRoleSchema,
  createUserSchema,
  setPasswordSchema,
  moduleAccessSchema,
  setGoogleEmailSchema,
  setAvatarSchema,
  ALLOWED_AVATAR_MIME_TYPES,
  MAX_AVATAR_BYTES,
  type CreateUserInput,
  type SetPasswordInput,
  type ModuleAccessInput,
  type SetGoogleEmailInput,
  type SetAvatarInput,
} from "./schema";
export type { UserRepository, NewUserRecord } from "./ports";
export {
  listUsers,
  createUser,
  verifyCredentials,
  setUserPassword,
  setUserRole,
  setUserDisabled,
  deleteUser,
  getUserByGoogleEmail,
  setUserGoogleEmail,
  createUserFromGoogle,
  isAdmin,
  getAccessibleModules,
  userHasModuleAccess,
  getUserModuleAccess,
  setUserModuleAccess,
  getUserAvatar,
  setUserAvatar,
  clearUserAvatar,
  DuplicateUsernameError,
  DuplicateGoogleEmailError,
  SelfLockoutError,
} from "./user";
