// Per-section reference for the Games module. Each section shows only the part that
// applies to it; Arcade carries the module-wide overview. Pure content, no state,
// rendered inside a collapsed CollapsibleCard so it's there when wanted and out of
// the way when not. Mirrors expense-instructions.tsx.

import type { GamesSection } from "./games-sections";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h3 className="font-display text-base text-ink">{title}</h3>
      <div className="mt-1 flex flex-col gap-2 text-sm text-muted">{children}</div>
    </section>
  );
}

function Key({ children }: { children: React.ReactNode }) {
  return (
    <kbd className="rounded border border-line px-1.5 py-0.5 font-mono text-xs text-ink">
      {children}
    </kbd>
  );
}

function ArcadeInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        A small arcade. Pick a game, play it in the browser, and your result goes onto a
        scoreboard shared by everyone in the house. Three games so far: 2048, the Arrow
        Clearing maze puzzle, and Tetris.
      </p>
      <Section title="How this module is laid out">
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">Arcade</strong> — the list of games, each with the
            current record and how many times it has been played.
          </li>
          <li>
            <strong className="text-ink">Scores</strong> — the full high-score board.
          </li>
          <li>
            <strong className="text-ink">Configuration</strong> — how the module behaves.
          </li>
        </ul>
      </Section>
      <Section title="Playing 2048">
        <p>
          Slide all the tiles one way; equal tiles that collide merge into their double, and
          the value of every merge is added to your score. A new tile appears after each move
          that actually shifted something. Reach the 2048 tile to win — you can keep going
          afterwards.
        </p>
        <p>
          Move with the <Key>←</Key> <Key>↑</Key> <Key>→</Key> <Key>↓</Key> arrow keys, or
          swipe on a touchscreen. Two rules worth knowing, because they are the ones that
          decide most games:
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            A gap between two equal tiles does <strong className="text-ink">not</strong> stop
            them merging — they slide together first.
          </li>
          <li>
            A tile merges at most once per move, so a row of four 2s becomes two 4s rather
            than a single 8.
          </li>
        </ul>
      </Section>
      <Section title="Playing Arrow Clearing">
        <p>
          The board is a 50&times;50 maze of about 360 arrows. Each one is a winding path of
          anything from two cells to a dozen with a head at the leading end. Tap it and it snakes off the board
          along its own route &mdash; but only if the straight line from its{" "}
          <strong className="text-ink">head</strong> to the edge is completely clear.
          Tapping shows you the route either way: green when the move was legal, red over
          whatever stood in the way when it was not.
        </p>
        <p>
          You have <strong className="text-ink">five lives</strong>, and every tap on an
          arrow that cannot move costs one. Run out and the board ends where it stands.
          So the puzzle is the order, not the reflexes:
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            Only the path <strong className="text-ink">in front of the head</strong>
            matters &mdash; nothing behind an arrow can hold it up. But watch for a path
            that curls back across its own lane: an arrow whose head points into its own
            tail cannot leave, and tapping it costs a life like any other blocked move.
          </li>
          <li>
            Scan for a head that already has open board ahead of it &mdash; those are the
            safe opening moves, and clearing one frees whatever it was standing in front
            of.
          </li>
          <li>
            A board can always be finished. Clearing an arrow only ever frees space, so no
            move can paint you into a corner: every puzzle is generated by shooting arrows
            in from the edges, and playing that back in reverse always works.
          </li>
          <li>
            <strong className="text-ink">Undo</strong> steps back one arrow and refunds a
            life if that move cost one. <strong className="text-ink">Hint</strong>{" "}
            highlights an arrow that can leave right now. Neither costs you anything.
          </li>
          <li>
            The board is large, so <strong className="text-ink">+</strong> and{" "}
            <strong className="text-ink">−</strong> zoom in for a closer look and{" "}
            <strong className="text-ink">Fit</strong> returns to the whole board. Drag to
            move around while zoomed. <strong className="text-ink">Show grid lines</strong>{" "}
            draws the lattice, which helps when checking whether an arrow and its blocker
            really share a row.
          </li>
        </ul>
        <p>
          Scoring is 100 a cleared arrow, less 15 for each wasted tap. A run that ends on
          lives still scores for the arrows it got out, so the number says how far you got.
        </p>
      </Section>

      <Section title="Playing Tetris">
        <p>
          Pieces fall one at a time into a 10&times;20 well. Fill a row all the way across
          and it clears, and everything above it drops down a line. Fill the well to the
          top and the run is over. This is the only game here with a{" "}
          <strong className="text-ink">clock</strong> &mdash; the pieces keep coming
          whether or not you have decided where to put them, and they come faster every
          ten lines.
        </p>
        <p>
          <Key>←</Key> <Key>→</Key> move, <Key>↑</Key> rotates, <Key>↓</Key> drops a row
          at a time, and <Key>Space</Key> slams the piece straight down and locks it.{" "}
          <Key>C</Key> puts the current piece aside for later, and <Key>P</Key> pauses.
          WASD works in place of the arrows, and on a phone there is a button pad under
          the board.
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">Clear four rows at once</strong> and you score
            800 rather than the 400 the same four rows pay one at a time. That is the
            whole reason to stack deep and keep a column open for a long piece &mdash;
            and the board flashes for a four-row clear, which the smaller ones do not.
          </li>
          <li>
            The outline at the bottom of the well shows where the current piece will
            land, so a hard drop is never a guess.
          </li>
          <li>
            A piece does not lock the instant it touches down &mdash; there is a moment
            to slide it sideways, which is how you tuck one under an overhang.
          </li>
          <li>
            Rotating against a wall <strong className="text-ink">nudges the piece</strong>{" "}
            clear rather than refusing, so a turn flush against the edge still works.
          </li>
          <li>
            Pieces are dealt a shuffled set of all seven at a time, so you will never be
            starved of a long piece for long &mdash; but you can hold one back with{" "}
            <Key>C</Key> once per piece.
          </li>
        </ul>
        <p>
          Scoring is the classic table: 100, 300, 500 and 800 for one to four rows,
          multiplied by your level, plus a point or two for every row you drop a piece
          yourself.
        </p>
      </Section>

      <Section title="When a score is saved">
        <p>
          At the end of a game: for 2048, when no move is left; for Arrow Clearing, when
          the board is empty or the lives run out; for Tetris, when the well fills to the
          top. Abandoning a game part-way saves nothing, so a refresh mid-game costs you
          the board rather than posting a low score.
        </p>
      </Section>
    </>
  );
}

function ScoresInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        Every finished game, best first. The board is deliberately{" "}
        <strong className="text-ink">shared</strong> rather than per-person: it answers
        &ldquo;who is best at this&rdquo;, so you see everyone&rsquo;s results and they see
        yours.
      </p>
      <Section title="Reading the board">
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>Ties are broken in favour of whoever got there first.</li>
          <li>
            A score is never edited or removed — a finished game is a historical fact. It also
            survives the account that set it being deleted, showing as{" "}
            <em>Unknown player</em> rather than vanishing.
          </li>
        </ul>
      </Section>
    </>
  );
}

function ConfigurationInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        There is nothing to configure yet. The list of games is part of the application
        rather than something stored, so a game appears here when it has been built — it
        cannot be added or removed from a screen.
      </p>
      <Section title="Why the game list isn't editable">
        <p>
          A game only exists if the code that draws it does. A row in a table naming a game
          this version cannot run would produce a card that goes nowhere, so the catalogue
          lives in the code beside the games themselves.
        </p>
      </Section>
    </>
  );
}

export function GamesInstructions({ section }: { section: GamesSection }) {
  if (section === "scores") return <ScoresInstructions />;
  if (section === "configuration") return <ConfigurationInstructions />;
  return <ArcadeInstructions />;
}
