// Per-section reference for the Games module. Each section shows only the part that
// applies to it; Arcade carries the module-wide overview. Pure content, no state,
// rendered inside a collapsed CollapsibleCard so it's there when wanted and out of
// the way when not. Mirrors expense-instructions.tsx.

import type { GamesSection } from "./games-sections";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h3 className="font-display text-base text-ink">{title}</h3>
      <div className="mt-1 flex flex-col gap-2 text-sm text-muted">{children}</div>
    </section>
  );
}

function Key({ children }: { children: React.ReactNode }) {
  return (
    <kbd className="rounded border border-line px-1.5 py-0.5 font-mono text-xs text-ink">
      {children}
    </kbd>
  );
}

function ArcadeInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        A small arcade. Pick a game, play it in the browser, and your result goes onto a
        scoreboard shared by everyone in the house. Six games so far: 2048, the Arrow
        Clearing maze puzzle, Tetris, Sudoku, Blackjack, and Minesweeper.
      </p>
      <Section title="How this module is laid out">
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">Arcade</strong> — the list of games, each with the
            current record and how many times it has been played.
          </li>
          <li>
            <strong className="text-ink">Scores</strong> — the full high-score board.
          </li>
          <li>
            <strong className="text-ink">Configuration</strong> — how the module behaves.
          </li>
        </ul>
      </Section>
      <Section title="Playing 2048">
        <p>
          Slide all the tiles one way; equal tiles that collide merge into their double, and
          the value of every merge is added to your score. A new tile appears after each move
          that actually shifted something. Reach the 2048 tile to win — you can keep going
          afterwards.
        </p>
        <p>
          Move with the <Key>←</Key> <Key>↑</Key> <Key>→</Key> <Key>↓</Key> arrow keys, or
          swipe on a touchscreen. Two rules worth knowing, because they are the ones that
          decide most games:
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            A gap between two equal tiles does <strong className="text-ink">not</strong> stop
            them merging — they slide together first.
          </li>
          <li>
            A tile merges at most once per move, so a row of four 2s becomes two 4s rather
            than a single 8.
          </li>
        </ul>
      </Section>
      <Section title="Playing Arrow Clearing">
        <p>
          The board is a 50&times;50 maze of about 360 arrows. Each one is a winding path of
          anything from two cells to a dozen with a head at the leading end. Tap it and it snakes off the board
          along its own route &mdash; but only if the straight line from its{" "}
          <strong className="text-ink">head</strong> to the edge is completely clear.
          Tapping shows you the route either way: green when the move was legal, red over
          whatever stood in the way when it was not.
        </p>
        <p>
          You have <strong className="text-ink">five lives</strong>, and every tap on an
          arrow that cannot move costs one. Run out and the board ends where it stands.
          So the puzzle is the order, not the reflexes:
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            Only the path <strong className="text-ink">in front of the head</strong>
            matters &mdash; nothing behind an arrow can hold it up. But watch for a path
            that curls back across its own lane: an arrow whose head points into its own
            tail cannot leave, and tapping it costs a life like any other blocked move.
          </li>
          <li>
            Scan for a head that already has open board ahead of it &mdash; those are the
            safe opening moves, and clearing one frees whatever it was standing in front
            of.
          </li>
          <li>
            A board can always be finished. Clearing an arrow only ever frees space, so no
            move can paint you into a corner: every puzzle is generated by shooting arrows
            in from the edges, and playing that back in reverse always works.
          </li>
          <li>
            <strong className="text-ink">Undo</strong> steps back one arrow and refunds a
            life if that move cost one. <strong className="text-ink">Hint</strong>{" "}
            highlights an arrow that can leave right now. Neither costs you anything.
          </li>
          <li>
            The board is large, so <strong className="text-ink">+</strong> and{" "}
            <strong className="text-ink">−</strong> zoom in for a closer look and{" "}
            <strong className="text-ink">Fit</strong> returns to the whole board. Drag to
            move around while zoomed. <strong className="text-ink">Show grid lines</strong>{" "}
            draws the lattice, which helps when checking whether an arrow and its blocker
            really share a row.
          </li>
        </ul>
        <p>
          Scoring is 100 a cleared arrow, less 15 for each wasted tap. A run that ends on
          lives still scores for the arrows it got out, so the number says how far you got.
        </p>
      </Section>

      <Section title="Playing Tetris">
        <p>
          Pieces fall one at a time into a 10&times;20 well. Fill a row all the way across
          and it clears, and everything above it drops down a line. Fill the well to the
          top and the run is over. This is the only game here with a{" "}
          <strong className="text-ink">clock</strong> &mdash; the pieces keep coming
          whether or not you have decided where to put them, and they come faster every
          ten lines.
        </p>
        <p>
          <Key>←</Key> <Key>→</Key> move, <Key>↑</Key> rotates, <Key>↓</Key> drops a row
          at a time, and <Key>Space</Key> slams the piece straight down and locks it.{" "}
          <Key>C</Key> puts the current piece aside for later, and <Key>P</Key> pauses.
          WASD works in place of the arrows, and on a phone there is a button pad under
          the board.
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">Clear four rows at once</strong> and you score
            800 rather than the 400 the same four rows pay one at a time. That is the
            whole reason to stack deep and keep a column open for a long piece &mdash;
            and the board flashes for a four-row clear, which the smaller ones do not.
          </li>
          <li>
            The outline at the bottom of the well shows where the current piece will
            land, so a hard drop is never a guess.
          </li>
          <li>
            A piece does not lock the instant it touches down &mdash; there is a moment
            to slide it sideways, which is how you tuck one under an overhang.
          </li>
          <li>
            Rotating against a wall <strong className="text-ink">nudges the piece</strong>{" "}
            clear rather than refusing, so a turn flush against the edge still works.
          </li>
          <li>
            Pieces are dealt a shuffled set of all seven at a time, so you will never be
            starved of a long piece for long &mdash; but you can hold one back with{" "}
            <Key>C</Key> once per piece.
          </li>
        </ul>
        <p>
          Scoring is the classic table: 100, 300, 500 and 800 for one to four rows,
          multiplied by your level, plus a point or two for every row you drop a piece
          yourself.
        </p>
      </Section>

      <Section title="Playing Sudoku">
        <p>
          Fill the 9&times;9 grid so every row, every column and every 3&times;3 box holds
          the digits one to nine exactly once. The digits printed when the board is dealt
          are fixed and cannot be changed; everything else is yours to work out. Pick{" "}
          <strong className="text-ink">Easy</strong>,{" "}
          <strong className="text-ink">Medium</strong> or{" "}
          <strong className="text-ink">Hard</strong> at the top &mdash; fewer starting
          digits means a harder board, and each one deals a new puzzle straight away.
        </p>
        <p>
          Tap a cell and then a digit, or use the keyboard: the arrow keys move around the
          grid, <Key>1</Key>&ndash;<Key>9</Key> enter a digit, <Key>Backspace</Key> clears
          a cell, <Key>N</Key> or <Key>Space</Key> switches to notes, and <Key>H</Key>
          takes a hint.
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">Notes</strong> pencil small candidates into a
            cell instead of answering it, for when you have narrowed a cell to two or
            three possibilities but cannot yet choose. Answering a cell clears its notes.
          </li>
          <li>
            <strong className="text-ink">Hint</strong> fills one cell in correctly. Select
            a cell first to be told that one, or press it with nothing selected and the
            game picks the cell you are closest to solving. If a cell already holds a
            wrong digit, that is what gets corrected. Hinted digits are shown in grey
            italics, so you can always see which answers were yours. There is no limit on
            hints &mdash; they cost points instead, see below.
          </li>
          <li>
            Selecting a cell highlights its row, column and box, and picking a cell that
            already holds a digit highlights every other copy of that digit &mdash; which
            is how you scan for where the next one has to go.
          </li>
          <li>
            A digit already placed nine times is greyed out on the pad, since no cell
            still wants one.
          </li>
          <li>
            <strong className="text-ink">A wrong digit is not refused.</strong> It goes on
            the board, in red, and counts as a mistake. Refusing it would let you find
            every answer by trying all nine and watching which one stuck.
          </li>
          <li>
            Every board has <strong className="text-ink">exactly one solution</strong>,
            guaranteed when it is generated &mdash; you will never need to guess between
            two valid answers.
          </li>
        </ul>
        <p>
          Sudoku scores <strong className="text-ink">points, not time</strong>, because the
          scoreboard ranks highest-first and a time in seconds would put the slowest player
          on top. A solve starts from the board&rsquo;s value &mdash; 2,000 easy, 3,500 medium,
          5,000 hard &mdash; and loses 4 points a second, 100 per mistake and 250 per
          hint, so a fast clean run scores best and a hard board beats an easy one for the
          same time. A hint costs more than a mistake on purpose: a wrong guess still
          leaves you to find the answer, a hint hands it over.
        </p>
        <p>
          A finish never scores less than 100, however long it took &mdash;{" "}
          <strong className="text-ink">unless you took a hint</strong>. Hints being
          unlimited, that floor would otherwise mean tapping <strong className="text-ink">
          Hint</strong> across the whole grid still banked 100 points for solving nothing,
          so the first hint removes it and a heavily hinted board can score all the way
          down to zero.
        </p>
      </Section>

      <Section title="Playing Blackjack">
        <p>
          Get closer to <strong className="text-ink">21</strong> than the dealer without
          going over. Court cards are worth ten and an ace is worth one or eleven,
          whichever suits your hand &mdash; so A&ndash;6 is a{" "}
          <strong className="text-ink">soft 17</strong> that can take a card without
          risk, and the total is shown both ways when it is soft.
        </p>
        <p>
          A run is a <strong className="text-ink">bankroll, not a hand</strong>. You sit
          down with 1,000 chips and bet between 25 and 250 a hand. The run ends when you
          cash out or when you cannot cover the minimum bet, and{" "}
          <strong className="text-ink">only a cash-out scores</strong> &mdash; going
          broke records nothing. Knowing when to get up is the game.
        </p>
        <p>
          <Key>H</Key> hits, <Key>S</Key> stands, <Key>D</Key> doubles, <Key>Enter</Key>{" "}
          deals the next hand, and <Key>↑</Key> <Key>↓</Key> change the bet. Every
          control is also a button, so a phone needs no keyboard.
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">The dealer stands on every 17</strong>, soft ones
            included, and draws on anything less. There is no judgement involved &mdash;
            you are playing against a rule you can see, which is what makes the decisions
            calculable.
          </li>
          <li>
            A <strong className="text-ink">blackjack</strong> &mdash; 21 on the first two
            cards &mdash; pays three to two rather than even money, and beats a dealer who
            reaches 21 with three cards. A 21 made after a split is just 21.
          </li>
          <li>
            <strong className="text-ink">Double</strong> doubles your stake for exactly
            one more card, and is only offered on your first two. It is the best bet on
            the table on a hard 10 or 11, and a poor one almost everywhere else.
          </li>
          <li>
            <strong className="text-ink">Split</strong> turns a matched pair into two
            hands, each with its own stake, played out in turn. Once per round, and only
            on a true pair &mdash; a king and a queen are both worth ten but are not one.
          </li>
          <li>
            <strong className="text-ink">Going bust loses immediately</strong>, even if
            the dealer then busts too. That is the whole of the house edge, and the reason
            standing on a stiff hand is sometimes right.
          </li>
          <li>
            Cards come from a six-deck shoe that is reshuffled between hands when it runs
            low, so counting what has gone will not get you far.
          </li>
        </ul>
        <p>
          Your score is the chips you walk away with, so a cautious run that banks 1,200
          beats a spectacular one that peaked at 4,000 and lost it. There is no insurance
          and no surrender: both are bets you should decline, and a button for a bad bet
          is just a trap.
        </p>
      </Section>

      <Section title="Playing Minesweeper">
        <p>
          Every square either hides a mine or does not. Uncover one and it shows how
          many of its eight neighbours are mined; uncover a mine and the run is over.
          Clear every safe square to win &mdash; the flags are a notepad, not the goal,
          and a board can be cleared without placing one. Pick{" "}
          <strong className="text-ink">Beginner</strong> (9&times;9, 10 mines),{" "}
          <strong className="text-ink">Intermediate</strong> (16&times;16, 40) or{" "}
          <strong className="text-ink">Expert</strong> (30&times;16, 99) at the top.
        </p>
        <p>
          Click to uncover and right-click to flag. On a phone, tap to uncover and{" "}
          <strong className="text-ink">hold</strong> to flag, or turn on{" "}
          <strong className="text-ink">Flag mode</strong> and every tap plants one
          instead.
        </p>
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>
            <strong className="text-ink">The first click is always safe</strong>, and so
            is everything touching it. The mines are laid after you click, avoiding that
            whole neighbourhood, so the opening move always opens up a region rather
            than being a one-in-five gamble. The clock starts there too.
          </li>
          <li>
            Uncovering a square with no mines around it{" "}
            <strong className="text-ink">cascades</strong>, opening its neighbours and
            theirs until it reaches numbers. Those numbers are the edge of what is
            known, and where the actual puzzle starts.
          </li>
          <li>
            Click a number whose mines you have all flagged and it{" "}
            <strong className="text-ink">clears everything else around it</strong> in one
            go. This is the move that makes Expert playable rather than 381 separate
            clicks &mdash; a satisfied number is outlined so you can see it is available.
            It is not a safety check, though: chord with a flag in the wrong place and
            you uncover a real mine.
          </li>
          <li>
            The mine counter is what is left after your flags, and it{" "}
            <strong className="text-ink">can go negative</strong> if you place more than
            there are. Nothing stops you &mdash; it is your notepad, and being told you
            are wrong before you have finished the deduction would give the answer away.
          </li>
          <li>
            A flagged square cannot be uncovered by accident, which is the practical
            reason to flag at all.
          </li>
        </ul>
        <p>
          Minesweeper scores <strong className="text-ink">points, not time</strong>, for
          the same reason Sudoku does: the board ranks highest-first, so seconds would
          put the slowest player on top. A clear starts from the board&rsquo;s value
          &mdash; 1,500 beginner, 3,500 intermediate, 6,000 expert &mdash; and loses 3
          points a second, so a fast clear scores best and an expert board beats a
          beginner one comfortably. A clear never scores less than 100. Hitting a mine
          scores nothing at all.
        </p>
      </Section>

      <Section title="When a score is saved">
        <p>
          At the end of a game: for 2048, when no move is left; for Arrow Clearing, when
          the board is empty or the lives run out; for Tetris, when the well fills to the
          top; for Sudoku, when the last cell is filled in correctly; for Blackjack, when
          you cash out or run out of chips; for Minesweeper, when the last safe square is
          uncovered. Abandoning a game part-way saves nothing, so a
          refresh mid-game costs you the board rather than posting a low score.
        </p>
      </Section>
    </>
  );
}

function ScoresInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        Every finished game, best first. The board is deliberately{" "}
        <strong className="text-ink">shared</strong> rather than per-person: it answers
        &ldquo;who is best at this&rdquo;, so you see everyone&rsquo;s results and they see
        yours.
      </p>
      <Section title="Reading the board">
        <ul className="flex list-disc flex-col gap-1 pl-5">
          <li>Ties are broken in favour of whoever got there first.</li>
          <li>
            A score is never edited or removed — a finished game is a historical fact. It also
            survives the account that set it being deleted, showing as{" "}
            <em>Unknown player</em> rather than vanishing.
          </li>
        </ul>
      </Section>
    </>
  );
}

function ConfigurationInstructions() {
  return (
    <>
      <p className="text-sm text-muted">
        There is nothing to configure yet. The list of games is part of the application
        rather than something stored, so a game appears here when it has been built — it
        cannot be added or removed from a screen.
      </p>
      <Section title="Why the game list isn't editable">
        <p>
          A game only exists if the code that draws it does. A row in a table naming a game
          this version cannot run would produce a card that goes nowhere, so the catalogue
          lives in the code beside the games themselves.
        </p>
      </Section>
    </>
  );
}

export function GamesInstructions({ section }: { section: GamesSection }) {
  if (section === "scores") return <ScoresInstructions />;
  if (section === "configuration") return <ConfigurationInstructions />;
  return <ArcadeInstructions />;
}
