import { randomUUID } from "node:crypto";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import type { SqliteFileStore } from "./ports";

/**
 * The uploaded files, in a workspace folder configured in wiring.ts.
 *
 * This is scratch space, not archival storage: the files here are copies a
 * reader brought in to poke at, and the module writes deletes back into them.
 * Wiping the folder is a supported thing to do — `exists` is checked before
 * every open, and a missing file reports "upload it again" rather than
 * throwing the driver's error.
 */
export class NodeSqliteFileStore implements SqliteFileStore {
  constructor(private readonly uploadRoot: string) {}

  /**
   * Writes the bytes under a generated name.
   *
   * The stored name is a UUID plus the original *extension* — never the
   * reader's own filename. Two people uploading `data.db` must not collide,
   * and a name off a file dialog can carry `..` or a path separator, so it is
   * kept for display only and never used to build a path.
   */
  async save(bytes: Uint8Array, originalFileName: string): Promise<string> {
    await mkdir(this.uploadRoot, { recursive: true });

    const extension = safeExtension(originalFileName);
    const storedFileName = `${randomUUID()}${extension}`;
    await writeFile(path.join(this.uploadRoot, storedFileName), bytes);

    return storedFileName;
  }

  pathFor(storedFileName: string): string {
    // The stored name is generated by `save`, but this is also reached with a
    // name read back out of the database, so it is re-checked rather than
    // trusted: `path.basename` strips any directory part a corrupted row could
    // be carrying, keeping every read inside the upload root.
    return path.join(this.uploadRoot, path.basename(storedFileName));
  }

  async exists(storedFileName: string): Promise<boolean> {
    try {
      const stats = await stat(this.pathFor(storedFileName));
      return stats.isFile();
    } catch {
      return false;
    }
  }

  async remove(storedFileName: string): Promise<void> {
    // `force` so removing an upload whose file a cleanup already took is a
    // no-op rather than an error — the caller's intent is "make it gone".
    await rm(this.pathFor(storedFileName), { force: true });
  }
}

/**
 * The original name's extension, if it is one we recognise.
 *
 * Anything else yields `.db`, so a stored name can never end in something the
 * OS treats specially. The schema has already restricted uploads to these.
 */
function safeExtension(originalFileName: string): string {
  const match = /\.(db|sqlite|sqlite3|db3)$/i.exec(originalFileName);
  return match ? `.${match[1].toLowerCase()}` : ".db";
}
