import { randomUUID } from "node:crypto";
import { createWriteStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { UploadTooLargeError } from "./errors";
import type { SqliteFileStore } from "./ports";

/**
 * The uploaded files, in a workspace folder configured in wiring.ts.
 *
 * This is scratch space, not archival storage: the files here are copies a
 * reader brought in to poke at, and the module writes deletes back into them.
 * Wiping the folder is a supported thing to do — `exists` is checked before
 * every open, and a missing file reports "upload it again" rather than
 * throwing the driver's error.
 */
export class NodeSqliteFileStore implements SqliteFileStore {
  constructor(private readonly uploadRoot: string) {}

  /**
   * Writes the bytes under a generated name.
   *
   * The stored name is a UUID plus the original *extension* — never the
   * reader's own filename. Two people uploading `data.db` must not collide,
   * and a name off a file dialog can carry `..` or a path separator, so it is
   * kept for display only and never used to build a path.
   */
  async save(bytes: Uint8Array, originalFileName: string): Promise<string> {
    await mkdir(this.uploadRoot, { recursive: true });

    const extension = safeExtension(originalFileName);
    const storedFileName = `${randomUUID()}${extension}`;
    await writeFile(path.join(this.uploadRoot, storedFileName), bytes);

    return storedFileName;
  }

  /**
   * Streams an upload to disk, enforcing the cap as it goes.
   *
   * The counter is checked per chunk rather than trusting Content-Length,
   * which is a claim the sender makes and can lie about. Passing the cap
   * aborts the write and removes the partial file, so an oversized upload
   * costs the disk `maxBytes` and a moment, not the sender's whole file.
   */
  async saveStream(
    stream: ReadableStream<Uint8Array>,
    originalFileName: string,
    maxBytes: number,
  ): Promise<{ storedFileName: string; byteSize: number }> {
    await mkdir(this.uploadRoot, { recursive: true });

    const storedFileName = `${randomUUID()}${safeExtension(originalFileName)}`;
    const destination = path.join(this.uploadRoot, storedFileName);

    let byteSize = 0;
    try {
      // `Readable.fromWeb` + `pipeline` gives backpressure for free: the
      // source is only pulled as fast as the disk accepts it.
      await pipeline(
        Readable.fromWeb(stream as Parameters<typeof Readable.fromWeb>[0]),
        async function* (source: AsyncIterable<Buffer>) {
          for await (const chunk of source) {
            byteSize += chunk.byteLength;
            if (byteSize > maxBytes) throw new UploadTooLargeError(maxBytes);
            yield chunk;
          }
        },
        createWriteStream(destination),
      );
    } catch (error) {
      // Includes a client that hung up mid-upload, which would otherwise leave
      // a truncated file that is not a valid database.
      await rm(destination, { force: true });
      throw error;
    }

    if (byteSize === 0) {
      await rm(destination, { force: true });
      throw new Error("That file is empty.");
    }

    return { storedFileName, byteSize };
  }

  pathFor(storedFileName: string): string {
    // The stored name is generated by `save`, but this is also reached with a
    // name read back out of the database, so it is re-checked rather than
    // trusted: `path.basename` strips any directory part a corrupted row could
    // be carrying, keeping every read inside the upload root.
    return path.join(this.uploadRoot, path.basename(storedFileName));
  }

  async exists(storedFileName: string): Promise<boolean> {
    try {
      const stats = await stat(this.pathFor(storedFileName));
      return stats.isFile();
    } catch {
      return false;
    }
  }

  async remove(storedFileName: string): Promise<void> {
    // `force` so removing an upload whose file a cleanup already took is a
    // no-op rather than an error — the caller's intent is "make it gone".
    await rm(this.pathFor(storedFileName), { force: true });
  }
}

/**
 * The original name's extension, if it is one we recognise.
 *
 * Anything else yields `.db`, so a stored name can never end in something the
 * OS treats specially. The schema has already restricted uploads to these.
 */
function safeExtension(originalFileName: string): string {
  const match = /\.(db|sqlite|sqlite3|db3)$/i.exec(originalFileName);
  return match ? `.${match[1].toLowerCase()}` : ".db";
}
