-- Repoints the Music Library module icon off the borrowed `heart` glyph.
--
-- 0053 seeded this module with `heart` as an acknowledged compromise: the right glyph
-- was a music note, MODULE_ICON_NAMES had none, and adding a concept means drawing it
-- for the hand-drawn "classic" set and naming a candidate in all 12 generated sets.
-- `music` — a beamed pair of eighth notes — is now that concept, so the compromise can
-- go.
--
-- Mirrored in src/lib/modules/defaults.ts (DEFAULT_MODULES) — keep both in sync, since
-- "Reset to Default" restores the table from that list.
--
-- Scoped by slug AND by the old value, as 0050 was: if someone has already picked a
-- different icon for this module, that choice is theirs and this migration leaves it
-- alone.
UPDATE sys_modules SET icon = 'music' WHERE slug = 'music-library' AND icon = 'heart';
