export type {
  CsvColumnType,
  CsvColumnDefinition,
  CsvAnalyticEntry,
  CsvEntryData,
  CsvChartPreset,
  CsvCustomView,
  CsvImportFile,
  CsvSourceColumn,
  MultiFileImportPlan,
  SourceStats,
  CsvSortDirection,
  CsvViewCriterion,
  CsvViewOperator,
  CsvViewOperatorArity,
  CsvViewOrderBy,
  CsvViewPage,
  IngestMode,
  IngestResult,
} from "./types";
export {
  csvColumnTypeSchema,
  csvColumnDefinitionSchema,
  ingestModeSchema,
  createCsvAnalyticEntrySchema,
  updateCsvAnalyticEntrySchema,
  saveChartPresetSchema,
  csvViewOperatorSchema,
  csvSortDirectionSchema,
  csvViewCriterionSchema,
  csvViewOrderBySchema,
  recordsPerPageSchema,
  createCsvCustomViewSchema,
  updateCsvCustomViewSchema,
  readCustomViewPageSchema,
  csvRowIdsSchema,
  csvBulkEditChangesSchema,
  csvBulkEditSchema,
  csvImportFileSchema,
  multiFileImportSchema,
  appendFilesSchema,
  type AppendFilesInput,
  type CsvImportFileInput,
  type MultiFileImportInput,
  type CsvBulkEditInput,
  type CsvBulkEditChanges,
  type CreateCsvAnalyticEntryInput,
  type UpdateCsvAnalyticEntryInput,
  type SaveChartPresetInput,
  type CreateCsvCustomViewInput,
  type UpdateCsvCustomViewInput,
  type ReadCustomViewPageInput,
} from "./schema";
export type { CsvAnalyticsRepository } from "./ports";
export {
  slugifyIdentifier,
  dedupeColumnNames,
  buildTableName,
  inferColumnType,
  coerceCellValue,
} from "./sql-builder";
export {
  previewCsvFile,
  listEntries,
  getEntryById,
  readEntryData,
  createEntry,
  updateEntry,
  deleteEntry,
  listChartPresets,
  saveChartPreset,
  deleteChartPreset,
  bulkEditRows,
  nonEditableColumns,
  planPooledImport,
  importPooledFiles,
  appendPooledFiles,
  readSourceStats,
  listSourceValues,
  type CsvAnalyticsPreview,
  type CsvBulkEditResult,
  type UpdateEntryResult,
} from "./csv-analytics";
export {
  CSV_VIEW_OPERATORS,
  CSV_VIEW_OPERATOR_ARITY,
  CSV_VIEW_OPERATOR_LABELS,
  operatorArity,
  compileViewQuery,
  resolveSelectedColumns,
  findUnknownColumns,
  findIncompleteCriteria,
  describeCriteria,
  describeOrderBy,
  type CompiledViewQuery,
  type CompileViewQueryInput,
} from "./view-query";
export {
  listCustomViews,
  listAllCustomViews,
  listEnabledCustomViews,
  getCustomViewById,
  createCustomView,
  updateCustomView,
  setCustomViewEnabled,
  deleteCustomView,
  readCustomViewPage,
} from "./custom-views";
export {
  SOURCE_FILE_COLUMN,
  MAX_SOURCE_LABEL_COLUMNS,
  suggestSourceName,
  buildSourceColumns,
  sourceColumnDefinitions,
  planMultiFileImport,
  buildPooledRows,
  groupableSourceColumns,
} from "./multi-import";
export {
  computeSourceStats,
  buildSourceSeries,
  buildSplitChartData,
  seriesKey,
  isMeasurableColumn,
  measurableColumns,
  type SourceStatsInput,
  type SourceStatsResult,
  type SourceSeries,
  type SourceSeriesPoint,
  type SplitChartData,
  type SplitSeries,
} from "./source-stats";
export {
  CSV_AGGREGATE_FUNCTIONS,
  CSV_AGGREGATE_LABELS,
  requiresNumericColumn,
  functionAcceptsColumn,
  columnsForFunction,
  applyFunction,
  describeAggregate,
  computeAggregates,
  aggregateReferenceLines,
  type CsvAggregateFunction,
  type CsvAggregateDefinition,
  type CsvAggregateResult,
  type AggregateReferenceLine,
  type ComputeAggregatesInput,
} from "./aggregates";
