export type {
  JournalEntry,
  EntryLocation,
  Weather,
  JournalCategory,
  JournalTag,
  JournalTaxonomyCount,
  JournalTaxonomyIcon,
  JournalFilter,
  JournalFilterCondition,
  JournalFilterGroup,
  JournalFilterField,
  JournalFilterOperator,
  JournalFilterJoin,
  SavedJournalFilter,
  TodayInHistoryEntry,
  JournalEntryRef,
  JournalEntryNeighbors,
  JournalPreferences,
  JournalDefaultLocation,
  JournalTemperatureUnit,
  JournalPrefillField,
  JournalPrefillMode,
  JournalPrefillFieldValue,
  JournalPrefillFormValues,
  JournalPrefillTemplate,
  RecycledJournalEntry,
} from "./types";
export {
  resolveJournalPreferences,
  journalPreferencesToEntries,
  JOURNAL_SETTING_KEYS,
} from "./preferences";
export {
  journalEntrySchema,
  entryLocationSchema,
  entryLocationInputSchema,
  weatherSchema,
  createEntrySchema,
  updateEntrySchema,
  journalCategorySchema,
  journalTagSchema,
  upsertCategorySchema,
  upsertTagSchema,
  MAX_JOURNAL_ICON_BYTES,
  JOURNAL_IMAGE_MIME_TYPES,
  journalFilterSchema,
  saveJournalFilterSchema,
  parseStoredJournalFilter,
  journalCalendarScopeSchema,
  journalDateFormatSchema,
  journalCalendarViewSchema,
  journalPrefillFieldSchema,
  journalPrefillModeSchema,
  journalPrefillFieldValueSchema,
  savePrefillTemplateSchema,
  parseStoredPrefillFields,
  JOURNAL_PREFILL_DYNAMIC_FIELDS,
  type JournalCalendarViewInput,
  type JournalCalendarView,
  type CreateEntryInput,
  type UpdateEntryInput,
  type EntryLocationInput,
  type UpsertCategoryInput,
  type UpsertTagInput,
  type SaveJournalFilterInput,
  type SavePrefillTemplateInput,
  type PrefillTemplateWriteData,
} from "./schema";
export {
  JOURNAL_CALENDAR_SCOPES,
  JOURNAL_DATE_FORMATS,
  DEFAULT_JOURNAL_DATE_FORMAT,
  CALENDAR_TITLE_MAX_LENGTH,
  CALENDAR_CELL_TITLE_LIMIT,
  CALENDAR_CELL_TITLE_LIMIT_COMPACT,
  WEEKDAY_LABELS,
  isJournalCalendarScope,
  isJournalDateFormat,
  journalCalendarRange,
  buildMonthGrid,
  buildWeekGrid,
  buildYearGrid,
  calendarEntryLabel,
  groupEntriesByDate,
  shiftCalendarAnchor,
  parseJumpDate,
  formatJumpDate,
  formatCalendarDayHeading,
  startOfWeek,
  startOfMonth,
  endOfMonth,
  type JournalCalendarScope,
  type JournalDateFormat,
  type CalendarEntryLabel,
  type CalendarEntryLike,
  type CalendarDay,
  type CalendarWeek,
  type CalendarMonth,
  type CalendarGrid,
  type CalendarYearGrid,
  type CalendarRange,
  type ParseJumpDateResult,
} from "./calendar";
export {
  parseFilterQuery,
  tryParseFilterQuery,
  FilterQueryError,
} from "./filter-query";
export {
  buildFilterSql,
  describeFilter,
  describeCondition,
  emptyFilter,
  isFilterEmpty,
  isRangeOperator,
  isValuelessOperator,
  isListOperator,
  OPERATORS_BY_FIELD,
  FIELD_LABELS,
} from "./filters";
export type { JournalEntryMatchKey, JournalRepository } from "./ports";
export { SqliteJournalRepository } from "./repository";
export {
  listEntries,
  listRecentEntries,
  listEntriesInDateRange,
  searchEntries,
  findEntries,
  listFilters,
  getFilter,
  saveFilter,
  deleteFilter,
  listTodayInHistory,
  getEntry,
  getEntryNeighbors,
  createEntry,
  updateEntry,
  deleteEntry,
  countAllEntries,
  clearAllEntries,
  type JournalEntryTally,
  setPinned,
  setLocked,
  listCategories,
  upsertCategory,
  deleteCategory,
  setCategoryIcon,
  clearCategoryIcon,
  getCategoryIcon,
  generateCategoryIcon,
  listTags,
  upsertTag,
  deleteTag,
  setTagIcon,
  clearTagIcon,
  getTagIcon,
  generateTagIcon,
  generateMissingTaxonomyIcons,
  type GenerateIconsSummary,
  type TaxonomyKind,
  listTopTags,
  listTopCategories,
} from "./journal";
export {
  GENERATED_ICON_MIME_TYPE,
  buildGeneratedIconSvg,
  isSafeGeneratedIconSvg,
  matchIconGlyph,
  iconTileColors,
  wrapIconBody,
} from "./generated-icons";
export { ICON_SET_PREFIX, iconifyIconId, matchIconName, looksLikePersonName } from "./icon-search";
export { fetchIconSvg, buildFetchedIconSvg, extractIconBody } from "./icon-fetch";
export type { FetchedIcon } from "./icon-fetch";
export {
  JOURNAL_PREFILL_FIELDS,
  PREFILL_SUGGESTION_LIMIT,
  prefillFieldLabel,
  prefillFieldAllowsNow,
  emptyPrefillValues,
  resolvePrefillValue,
  applyPrefillTemplate,
  listPrefillTemplates,
  listEnabledPrefillTemplates,
  getPrefillTemplate,
  getPrefillTemplateByName,
  savePrefillTemplate,
  deletePrefillTemplate,
  setPrefillTemplateEnabled,
  listPrefillSuggestions,
} from "./prefill";
export {
  importJournalCsv,
  planJournalImport,
  autoMapJournalHeaders,
  JOURNAL_IMPORT_FIELDS,
} from "./csv-import";
export type {
  JournalImportAction,
  JournalImportOptions,
  JournalImportPlan,
  JournalImportPlanRow,
} from "./csv-import";
export { normalizeEntryTime } from "./time";

// Metadata backup and restore — the categories, tags, icons, templates, filters
// and preferences behind the Meta Data section's "Back up all meta data" button.
// Entries are not part of this; they have the CSV path above.
export {
  JOURNAL_METADATA_FORMAT,
  JOURNAL_METADATA_FORMAT_VERSION,
  journalMetadataBundleSchema,
  parseMetadataBundle,
  metadataExportFileName,
  buildMetadataBundle,
  serializeMetadataBundle,
  planMetadataImport,
  applyMetadataImport,
  metadataPreferenceEntries,
} from "./metadata-export";
export type {
  JournalMetadataBundle,
  JournalMetadataIcon,
  JournalMetadataTaxonomy,
  JournalMetadataAction,
  JournalMetadataPlan,
  JournalMetadataPlanRow,
  JournalMetadataRestoreSummary,
} from "./metadata-export";

// Duplicate finding for the Correct tab. Pure functions over a list of entries
// — no repository, so the view can re-group a snapshot without a round trip.
export {
  DUPLICATE_EXCERPT_WORDS,
  countDuplicateEntries,
  excerptWords,
  findDuplicateGroups,
  toDuplicateRows,
} from "./duplicates";
export type { DuplicateEntry, DuplicateGroup, DuplicateRow } from "./duplicates";

// The recycle bin behind the Correct tab's bulk delete (migration 0079).
export {
  countRecycledEntries,
  deleteRecycledEntriesForever,
  emptyRecycleBin,
  listRecycledEntries,
  recycleEntries,
  restoreRecycledEntries,
} from "./recycle";
export type { PurgeResult, RecycleResult, RestoreResult } from "./recycle";
