export {
  TRANSACTION_STATUSES,
  RULE_ACTION_FIELDS,
  RULE_ACTION_FIELD_LABELS,
  type TransactionStatus,
  type CreditCardAccount,
  type ExpenseCategory,
  type ExpenseTransaction,
  type PostImportRule,
  type RuleAction,
  type RuleActionField,
  type CategoryTotal,
  type VendorTotal,
  type CardImage,
  type CategoryIcon,
} from "./types";
export {
  transactionStatusSchema,
  creditCardAccountSchema,
  saveAccountSchema,
  expenseCategorySchema,
  saveCategorySchema,
  expenseTransactionSchema,
  saveTransactionSchema,
  postImportRuleSchema,
  savePostImportRuleSchema,
  bulkTransactionEditSchema,
  transactionIdsSchema,
  ruleActionSchema,
  saveRuleActionSchema,
  ruleActionFieldSchema,
  expenseImageUploadSchema,
  EXPENSE_IMAGE_MIME_TYPES,
  MAX_CARD_IMAGE_BYTES,
  MAX_CATEGORY_ICON_BYTES,
  type ExpenseImageUploadInput,
  type SaveAccountInput,
  type SaveCategoryInput,
  type SaveTransactionInput,
  type SavePostImportRuleInput,
  type BulkTransactionEditInput,
  type AccountWriteData,
  type CategoryWriteData,
  type TransactionWriteData,
  type BulkTransactionEditData,
  type PostImportRuleWriteData,
} from "./schema";
export type { ExpenseRepository, TransactionFilter } from "./ports";
export { SqliteExpenseRepository } from "./repository";
export {
  compilePattern,
  matchesPattern,
  findMatchingRule,
  planRuleApplication,
  applyAssignments,
  type RulePlan,
  type PlannedAssignment,
} from "./rules";
export {
  listAccounts,
  createAccount,
  updateAccount,
  deleteAccount,
  setAccountImage,
  clearAccountImage,
  getAccountImage,
  listCategories,
  upsertCategory,
  deleteCategory,
  setCategoryIcon,
  clearCategoryIcon,
  getCategoryIcon,
  listTransactions,
  getTransaction,
  createTransaction,
  updateTransaction,
  deleteTransaction,
  deleteTransactions,
  bulkEditTransactions,
  listRules,
  createRule,
  updateRule,
  deleteRule,
  runCleanupBatch,
  countUnprocessed,
  resetProcessedFlags,
  previewPatternMatches,
  totalsByCategory,
  DEFAULT_CLEANUP_BATCH_SIZE,
  type CleanupBatchResult,
  type CleanupLogEntry,
} from "./expense";
export {
  totalsByVendor,
  vendorTotals,
  vendorGroupKey,
  vendorKeyFromDescription,
} from "./vendors";
export {
  EXPENSE_SETTING_KEYS,
  DEFAULT_AUTO_IMPORT_INTERVAL_MINUTES,
  resolveExpenseSettings,
  expenseSettingsToEntries,
  isAutoImportConfigured,
  isAutoImportEnabled,
  shouldRunNow,
  type ExpenseSettings,
} from "./settings";
// Only the interface: the Node implementation imports node:fs, and this barrel
// is reachable from client components (they import the domain types from it),
// which would drag a filesystem module into the browser bundle. wiring.ts
// imports NodeCsvFolder from "./expense/csv-folder" directly instead.
export type { CsvFolderPort } from "./csv-folder";
export {
  runAutoImport,
  accountNameFromFolderName,
  findMappingForAccount,
  type AutoImportRunSummary,
  type AutoImportFileResult,
  type AutoImportDependencies,
} from "./auto-import";
export {
  importExpenseCsv,
  parseMoneyToCents,
  EXPENSE_IMPORT_FIELDS,
  type ExpenseImportOptions,
  type ExpenseImportSummary,
} from "./csv-import";
