// The Games module's front door. Everything outside src/lib/games imports from here.
export {
  ARROW_DIFFICULTIES,
  ARROW_DIFFICULTY_SETUP,
  ARROW_LIVES,
  BOARD_SIZE,
  BUFFER_ROWS,
  DIRECTIONS,
  HARD_DROP_POINTS,
  LINES_PER_LEVEL,
  LINE_SCORES,
  LOCK_DELAY_TICKS,
  PIECE_KINDS,
  PLAYFIELD_HEIGHT,
  PLAYFIELD_WIDTH,
  SOFT_DROP_POINTS,
  TOTAL_HEIGHT,
  WINNING_TILE,
  arrowDifficultyOf,
  type ActivePiece,
  type Arrow,
  type ArrowBoard,
  type ArrowDifficulty,
  type ArrowPuzzle,
  type ArrowState,
  type Board,
  type CatalogueGame,
  type Cell,
  type Direction,
  type GameStatus,
  type LineClear,
  type MoveResult,
  type PieceCell,
  type PieceKind,
  type Playfield,
  type Rotation,
  type Score,
  type TetrisOutcome,
  type TetrisState,
} from "./types";
export { GAME_CATALOGUE, findGame, isKnownGame, listPlayableGames } from "./catalogue";
export {
  moveSchema,
  recordScoreSchema,
  topScoresQuerySchema,
  type MoveInput,
  type RecordScoreInput,
  type ScoreWriteData,
  type TopScoresQuery,
} from "./schema";
export type { ScoreRepository } from "./ports";
export {
  formatScore,
  getGame,
  listAvailableGames,
  listGames,
  listRecentScores,
  listTopScores,
  recordScore,
  type GameSummary,
} from "./games";
export {
  applyMove,
  canMove,
  collapseLine,
  emptyBoard,
  emptyCells,
  hasWon,
  highestTile,
  isGameOver,
  spawnTile,
  startBoard,
  type Random,
} from "./game-2048";
export {
  MAX_ARROW_LENGTH,
  MIN_ARROW_LENGTH,
  clearArrow,
  generatePuzzle,
  isBlocked,
  isOnBoard,
  isSolved,
  isStuck,
  pathAhead,
  scoreBoard,
  solutionClearsBoard,
  step,
  unblockedArrows,
} from "./game-arrows";
export {
  PREVIEW_COUNT,
  canPlace,
  cellsOf,
  clearLines,
  dropIntervalMs,
  emptyField,
  ghostPiece,
  hardDrop,
  holdPiece,
  isLanded,
  levelFor,
  lockPiece,
  moveHorizontal,
  renderRows,
  rotate,
  softDrop,
  spawnPiece,
  startGame,
  tick,
} from "./game-tetris";
