// The Games module's front door. Everything outside src/lib/games imports from here.

// The deck primitives, shared by every card game and by the `PlayingCard` /
// `CardHand` components. Game-agnostic — nothing here knows what a card is worth.
export {
  CARDS_IN_DECK,
  COURT_RANKS,
  RANKS,
  SUITS,
  buildShoe,
  draw,
  isCourt,
  isRedSuit,
  newDeck,
  shuffle,
  shuffledShoe,
} from "./playing-cards";
// The mahjong tile set — the tile twin of the deck above, and game-agnostic for the same
// reason: nothing here knows what a tile scores. Rendered by the `MahjongTile` /
// `MahjongWall` components.
//
// `shuffle` and `draw` are the collisions, since a deck exports both under those names.
// The tile versions are aliased here for the reason the game blocks below are: inside
// `mahjong-tiles.ts` the short names are the clear ones, and only this file, where every
// surface meets, needs the qualifier. The two `shuffle`s are the same generic function
// duplicated rather than shared — a deck and a tile set are independent primitives, and
// a common `src/lib/games/shuffle.ts` is worth adding only if a third one appears.
export {
  BONUS_KINDS,
  BONUS_TILES,
  COPIES_PER_TILE,
  DISTINCT_TILES,
  DRAGONS,
  FLOWERS,
  HONOUR_KINDS,
  SEASONS,
  TILES_IN_SET,
  TILE_RANKS,
  TILE_SUITS,
  WINDS,
  buildWall,
  draw as drawTiles,
  groupByFace,
  isBonus,
  isHonour,
  isSimple,
  isTerminal,
  matches as tilesMatch,
  shuffle as shuffleTiles,
  shuffledWall,
  sortTiles,
  tileFace,
} from "./mahjong-tiles";
export {
  ARROW_DIFFICULTIES,
  ARROW_DIFFICULTY_SETUP,
  ARROW_LIVES,
  BLACKJACK_BET_STEP,
  BLACKJACK_MAX_BET,
  BLACKJACK_MIN_BET,
  BLACKJACK_PAYOUT,
  BLACKJACK_STARTING_CHIPS,
  BLACKJACK_TARGET,
  BOARD_SIZE,
  BUFFER_ROWS,
  DEALER_STANDS_ON,
  DECKS_IN_SHOE,
  DIRECTIONS,
  HAND_SIZE,
  HARD_DROP_POINTS,
  HUMAN_SEAT,
  LINES_PER_LEVEL,
  LINE_SCORES,
  LOCK_DELAY_TICKS,
  MAHJONG_ACTIONS,
  MAHJONG_BASE_FAN,
  MAHJONG_FIGURES,
  MAHJONG_FLOWER_FAN,
  MAHJONG_MATCH_DIFFICULTIES,
  MAHJONG_MATCH_HINT_PENALTY,
  MAHJONG_MATCH_MIN_SCORE,
  MAHJONG_MATCH_SETUP,
  MAHJONG_MATCH_SHUFFLE_PENALTY,
  MAHJONG_MATCH_TIME_PENALTY,
  MAHJONG_MAX_FAN,
  MAHJONG_PHASES,
  MAHJONG_POINTS_PER_FAN,
  MINESWEEPER_DIFFICULTIES,
  MINESWEEPER_MIN_SCORE,
  MINESWEEPER_SETUP,
  MINESWEEPER_TIME_PENALTY,
  PIECE_KINDS,
  PLAYFIELD_HEIGHT,
  PLAYFIELD_WIDTH,
  SEATS,
  SHOE_RESHUFFLE_AT,
  SOFT_DROP_POINTS,
  SUDOKU_BOX,
  SUDOKU_CELL_COUNT,
  SUDOKU_DIFFICULTIES,
  SUDOKU_HINT_PENALTY,
  SUDOKU_MIN_SCORE,
  SUDOKU_MISTAKE_PENALTY,
  SUDOKU_SETUP,
  SUDOKU_SIZE,
  SUDOKU_TIME_PENALTY,
  TOTAL_HEIGHT,
  WINNING_TILE,
  arrowDifficultyOf,
  type ActivePiece,
  type Arrow,
  type ArrowBoard,
  type ArrowDifficulty,
  type ArrowPuzzle,
  type ArrowState,
  type BlackjackOutcome,
  type BlackjackPhase,
  type BlackjackState,
  type Board,
  type BoardTile,
  type Card,
  type CatalogueGame,
  type Cell,
  type Direction,
  type Dragon,
  type Flower,
  type GameStatus,
  type Hand,
  type HandResult,
  type LineClear,
  type MahjongCall,
  type MahjongFan,
  type MahjongHand,
  type MahjongLayoutName,
  type MahjongMatchDifficulty,
  type MahjongMatchOutcome,
  type MahjongMatchState,
  type MahjongOutcome,
  type MahjongPhase,
  type MahjongScore,
  type MahjongState,
  type Meld,
  type MeldKind,
  type MinesweeperCell,
  type MinesweeperDifficulty,
  type MinesweeperOutcome,
  type MinesweeperState,
  type MoveResult,
  type PieceCell,
  type PieceKind,
  type Playfield,
  type Rank,
  type Rotation,
  type Seat,
  type Score,
  type Season,
  type Suit,
  type SudokuCell,
  type SudokuDifficulty,
  type SudokuDigit,
  type SudokuGrid,
  type SudokuOutcome,
  type SudokuState,
  type TetrisOutcome,
  type TetrisState,
  type Tile,
  type TileKind,
  type TileRank,
  type TilePosition,
  type TileSuit,
  type Wind,
} from "./types";
export { GAME_CATALOGUE, findGame, isKnownGame, listPlayableGames } from "./catalogue";
export {
  moveSchema,
  recordScoreSchema,
  topScoresQuerySchema,
  type MoveInput,
  type RecordScoreInput,
  type ScoreWriteData,
  type TopScoresQuery,
} from "./schema";
export type { ScoreRepository } from "./ports";
export {
  formatScore,
  getGame,
  listAvailableGames,
  listGames,
  listRecentScores,
  listTopScores,
  recordScore,
  type GameSummary,
} from "./games";
export {
  applyMove,
  canMove,
  collapseLine,
  emptyBoard,
  emptyCells,
  hasWon,
  highestTile,
  isGameOver,
  spawnTile,
  startBoard,
  type Random,
} from "./game-2048";
export {
  MAX_ARROW_LENGTH,
  MIN_ARROW_LENGTH,
  clearArrow,
  generatePuzzle,
  isBlocked,
  isOnBoard,
  isSolved,
  isStuck,
  pathAhead,
  scoreBoard,
  solutionClearsBoard,
  step,
  unblockedArrows,
} from "./game-arrows";
export {
  PREVIEW_COUNT,
  canPlace,
  cellsOf,
  clearLines,
  dropIntervalMs,
  emptyField,
  ghostPiece,
  hardDrop,
  holdPiece,
  isLanded,
  levelFor,
  lockPiece,
  moveHorizontal,
  renderRows,
  rotate,
  softDrop,
  spawnPiece,
  startGame,
  tick,
} from "./game-tetris";
// Sudoku. `canPlace`, `renderRows`, `startGame` and `tick` are also Tetris exports, so
// the Sudoku ones are aliased rather than renamed in their own module: inside
// `game-sudoku.ts` the short names are the clear ones, and it is only here, where every
// game's surface meets, that they need a qualifier. `Random` is already exported above
// from `game-2048` and is the same structural type, so it is not re-exported.
export {
  canPlace as canPlaceDigit,
  candidatesFor as sudokuCandidatesFor,
  clearCell,
  countSolutions,
  digitCount,
  emptyGrid,
  enterDigit,
  hasUniqueSolution,
  hintTarget as sudokuHintTarget,
  hintedCells,
  isSolved as isSudokuSolved,
  peersOf,
  removeClues,
  renderRows as renderSudokuRows,
  revealHint,
  scoreGame,
  solvedGrid,
  startGame as startSudoku,
  tick as tickSudoku,
  toggleNote,
  wrongCells,
} from "./game-sudoku";
// Blackjack. `startGame`, `scoreGame`, `split` and `deal` are the collisions this time
// — `startGame` with three other games and `scoreGame` with Sudoku — so they are
// aliased here for the same reason the Sudoku block above is: inside
// `game-blackjack.ts` the short names read best, and only this file, where every
// game's surface meets, needs the qualifier. `Random` is already exported from
// `game-2048` and is the same structural type, so it is not re-exported.
export {
  activeHandOf,
  canDouble,
  canSplit,
  cashOut,
  clampBet,
  deal as dealBlackjack,
  dealerPlay,
  dealerUpcard,
  doubleDown,
  handValue,
  hit,
  isBlackjack,
  isBust,
  newShoe,
  nextRound,
  scoreGame as scoreBlackjack,
  setBet,
  settle,
  split,
  stand,
  startGame as startBlackjack,
  totalOf,
  valueOf,
} from "./game-blackjack";
// Minesweeper. `startGame`, `scoreGame`, `tick`, `renderRows` and `reveal` are the
// collisions this time — `scoreGame` is already taken by Sudoku, which exports it
// unaliased — so the Minesweeper ones are qualified here for the reason the two blocks
// above are: inside `game-minesweeper.ts` the short names read best, and only this
// file, where every game's surface meets, needs the qualifier. `Random` is already
// exported from `game-2048` and is the same structural type, so it is not re-exported.
export {
  canChord,
  chord,
  isCleared,
  layMines,
  minesRemaining,
  neighboursOf,
  renderRows as renderMinesweeperRows,
  reveal as revealCell,
  scoreGame as scoreMinesweeper,
  startGame as startMinesweeper,
  tick as tickMinesweeper,
  toggleFlag,
} from "./game-minesweeper";
// Mahjong Match. `startGame`, `scoreGame` and `tick` are the collisions again, plus
// `undo` and `findPair` which are new. Aliased here for the reason the blocks above are:
// inside `game-mahjong-match.ts` the short names read best, and only this file, where
// every game's surface meets, needs the qualifier. `Random` is already exported from
// `game-2048` and is the same structural type, so it is not re-exported.
export {
  TILE_SPAN,
  boardBounds,
  canShuffle,
  faceSet,
  findPair,
  freeTiles,
  hasMove,
  isFree,
  MAHJONG_LAYOUTS,
  layoutPositions,
  paintOrder,
  reshuffle,
  scoreGame as scoreMahjongMatch,
  selectTile,
  startGame as startMahjongMatch,
  takeHint,
  tick as tickMahjongMatch,
  tilesLeft,
  undo as undoMahjongMatch,
} from "./game-mahjong-match";

// Mahjong — the four-player tile game against three bots. The collisions this time are
// `startGame`, `scoreGame`, `drawTile`/`draw` and `tileValue`; aliased here for the
// reason every block above is, that inside `game-mahjong.ts` the short names read best
// and only this file, where every game's surface meets, needs the qualifier. `Random` is
// already exported from `game-2048` and is the same structural type, so it is not
// re-exported.
//
// `getAvailableCalls`, `resolveCalls` and `stepBots` are unique to this game and keep
// their names.
export {
  allTiles as allMahjongTiles,
  applyCall,
  botAcceptsCall,
  botCall,
  botDiscard,
  canDeclareWin,
  claimOrder,
  collectCalls,
  concealedKongOptions,
  declareConcealedKong,
  declareSelfWin,
  discardTile,
  drawTile as drawMahjongTile,
  getAvailableCalls,
  getSanitizedState,
  handFans,
  handOf,
  isHandOver,
  isHumanSeat,
  isOneAway,
  isSevenPairs,
  isWaitingForHuman,
  isWinningHand,
  leftOf,
  nextSeat,
  passCalls,
  replaceBonusTiles,
  resolveCalls,
  scoreGame as scoreMahjong,
  scoreHand as scoreMahjongHand,
  startGame as startMahjong,
  stepBots,
  tileValue,
  tilesLeft as mahjongTilesLeft,
  windOf,
  winningWaits,
  SEAT_WINDS,
  type MahjongViewState,
} from "./game-mahjong";
